[package]
name = "tx"
description = "contention-aware speculative software transactional memory"
version = "0.1.2"
authors = ["Tyler Neely <t@jujit.su>"]
edition = "2018"

[features]
default = []

[dependencies]
lazy_static = "1.4.0"
